---
- name: Deploy Docker Compose stack
  hosts: localhost
  remote_user: SVP
  become: true

  tasks:
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Pull Backend Image
      docker_image:
        name: svp3012/betr-backend
        source: pull

    - name: Pull Frontend Image
      docker_image:
        name: svp3012/betr-frontend-app
        source: pull

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/BETr/docker-compose.yml
        dest: /opt/docker-compose.yml

    - name: Start Docker Compose stack
      command: docker-compose up -d
      args:
        chdir: /opt/

    - name: Run Backend Container
      docker_container:
        name: betr-backend
        image: svp3012/betr-backend
        state: started
        ports:
          - "8081:8081"  

    - name: Run Frontend Container
      docker_container:
        name: betr-frontend-app
        image: svp3012/betr-frontend-app
        state: started
        ports:
          - "3000:3000"  
        env:
          REACT_APP_API_URL: "http://127.0.0.1:8081"
          REACT_APP_DEBUG: "true"
