# version: '3.9'
# networks:
#   betr-network:
# volumes:
#   database-volume:
#   logs:
# services:
#   mydb:
#     image: mysql:latest
#     restart: always
#     healthcheck:
#       test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     container_name: database-container
#     environment:
#       - MYSQL_ROOT_PASSWORD: 3012
#       - MYSQL_DATABASE: betr
#       - MYSQL_USER: svp
#       - MYSQL_PASSWORD: Taehyungieoppa@3012
#     ports:
#       - "3306:3306"
#     volumes:
#       - database-volume:/var/lib/mysql
#     networks:
#       - betr-network
#   betr-backend:
#     image: svp3012/betr-backend
#     container_name: betr-backend
#     user: "svp"
#     ports:
#       - "8081:8081"
#     environment:
#       MYSQL_URL: jdbc:mysql://mydb/betr?createDatabaseIfNotExist=true
#       MYSQL_USERNAME: svp
#       MYSQL_PASSWORD: Taehyungieoppa@3012
#     volumes:
#       - logs:/logs
#     networks:
#       - betr-network
#     depends_on:
#       mydb:
#         condition: service_healthy
#   betr-frontend:
#     image: svp3012/betr-frontend-app
#     container_name: betr-frontend-app
#     stdin_open: true
#     ports:
#       - "3000:3000"
#     networks:
#       - betr-network
#     depends_on:
#       - betr-backend
version: '3.9'
networks:
  betr-network:

volumes:
  database-volume:
  logs:

services:
  mydb:
    image: mysql:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: "3012"
      MYSQL_DATABASE: "betr"
      MYSQL_USER: "svp"
      MYSQL_PASSWORD: "Taehyungieoppa@3012"
    ports:
      - "3307:3306"
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - betr-network

  betr-backend:
    image: svp3012/betr-backend
    container_name: betr-backend
    user: "svp"
    ports:
      - "8081:8081"
    environment:
      MYSQL_URL: "jdbc:mysql://mydb/betr?createDatabaseIfNotExist=true"
      MYSQL_USERNAME: "svp"
      MYSQL_PASSWORD: "Taehyungieoppa@3012"
    volumes:
      - logs:/logs
    networks:
      - betr-network
    depends_on:
      mydb:
        condition: service_healthy

  betr-frontend:
    image: svp3012/betr-frontend-app
    container_name: betr-frontend-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - betr-network
    depends_on:
      - betr-backend
