version: '3.9'
services:
  betr-backend:
      image: svp3012/betr-backend
      container_name: betr-backend
      ports:
        - "8082:8081"
      environment:
        SPRING_DATASOURCE_URL: "jdbc:mysql://betrDB:3306/betr?createDatabaseIfNotExist=true"
        # SPRING_DATASOURCE_USERNAME: "root"
        # SPRING_DATASOURCE_PASSWORD: "3012"
        SPRING_DATASOURCE_USERNAME: "svp"
        SPRING_DATASOURCE_PASSWORD: "Taehyungieoppa@3012"
      networks:
        - betr-network
      depends_on:
        - betrDB
  betrDB:
    image: mysql:8
    container_name: betrDB
    environment:
      MYSQL_ROOT_PASSWORD: "3012"
      MYSQL_DATABASE: "betr"
      # MYSQL_USER: "svp"
      # MYSQL_PASSWORD: "Taehyungieoppa@3012"
    ports:
      - "3307:3306"
    volumes:
      - betrDB:/var/lib/mysql
    networks:
      - betr-network

  betr-frontend:
    image: svp3012/betr-frontend-app
    container_name: betr-frontend-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - betr-network

networks:
  betr-network:
    driver: bridge

volumes:
  betrDB:
