version: '3.9'
networks:
  betr-network:
    driver: bridge

volumes:
  betrDB:
  logs:

services:
  betr-backend:
      image: svp3012/betr-backend
      container_name: betr-backend
      # user: "svp"
      ports:
        - "8081:8081"
      environment:
        SPRING_DATASOURCE_URL: "jdbc:mysql://172.23.0.2:3306/betr?createDatabaseIfNotExist=true"
        SPRING_DATASOURCE_USERNAME: "svp"
        SPRING_DATASOURCE_PASSWORD: "Taehyungieoppa@3012"
      volumes:
        - logs:/logs
      networks:
        - betr-network
      depends_on:
        - mydb
          # condition: service_healthy
  mydb:
    # image: mysql:latest
    image: mysql:8
    # restart: always
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    container_name: betrDB
    environment:
      MYSQL_ROOT_PASSWORD: "3012"
      MYSQL_DATABASE: "betr"
      # MYSQL_USER: "svp"
      # MYSQL_PASSWORD: "Taehyungieoppa@3012"
    ports:
      - "3307:3306"
    volumes:
      - betrDB:/var/lib/mysql
    networks:
      - betr-network

  betr-frontend:
    image: svp3012/betr-frontend-app
    container_name: betr-frontend-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - betr-network
    # depends_on:
    #   - betr-backend
